language: java

jdk:
  - openjdk8
  # CI still fails with FindBugs on Oracle JDK11
  # It seems time to move to SpotBugs, but I'm disbling CI on JDK11 for now...
  # - oraclejdk11

install:
  - ./gradlew assemble -x signArchives -x uploadArchives

script:
  - ./gradlew check --debug --stacktrace --info

after_success:
  - ./gradlew jacocoTestReport coveralls
