language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_script:
  - echo 'hello, world'
  - ./gradlew assemble -x signArchives -x uploadArchives

script:
  - ./gradlew check
